#!/bin/sh

# Created By: Javier Pacheco - jpacheco@cock.li
# Created On: 13/04/24
# Project: toggle animations in hyprland

HYPRANIM=$(hyprctl getoption animations:enabled | awk 'NR==1{print $2}')
if [ "$HYPRANIM" = 0 ] ; then
    hyprctl --batch "\
        keyword animations:enabled 1"
    notify-send "Animations are now enabled"
    else
    hyprctl --batch "\
        keyword animations:enabled 0"
    notify-send "Animations are now disabled"
    exit
fi
hyprctl reload
