#+TITLE: Hyprland Scripts
#+AUTHOR: Javier Pacheco / Linuxero (linuxeando)
#+DATE: 2024-07-27
#+OPTIONS: toc:nil

* Overview
This directory contains shell scripts specifically tailored for managing and enhancing the Hyprland window manager on Wayland. Each script offers different functionalities to improve the user experience.

* Scripts

1. hypr-gaps
   - *Description*: This script manages the gaps between windows, allowing you to adjust the space around windows for a cleaner look.
   - *Usage*: Run =hypr-gaps [option]= to set the gap size. Replace =[size]= with the desired gap option:
     - -i :: increment.
     - -d :: decrement.
     - -r :: reset to the deafult gap set in your =hyprland.conf= 

2. hypr-scratchpads
   - *Description*: Implements a scratchpad functionality, allowing you to toggle specific applications on and off the screen, making them easily accessible but hidden when not needed.
   - *Usage*: Run =hypr-scratchpads [command]=. Use =[command]= to specify the application or action (e.g. =hypr-scratchpads terminal=).
This scripts works hand on hand within your window rules settings in your =hyprland.conf= file; here are some examples:

#+begin_src conf
# scratchpads rules! floating and center always
$scratchpad = class:^(scratchpad)$
windowrulev2 = float,$scratchpad
windowrulev2 = center,$scratchpad
#+end_src

3. hypr-animations
   - *Description*: Controls the animation settings for window transitions, providing a smoother visual experience.
   - *Usage*: Run =hypr-animations= to turn animations on or off.

4. hypr-screenrecord.
   - *Description*: This scripts uses tofi as a menu to record the screen. It have 3 modes of recording:
     - screencast -> This record the whole screen.
     - area -> This use =slurp= to select a section of the screen.
     - share -> This will upload the recorded video to =0x0.st=.
     The scripts will record the audio of the sound card, this means that if you are listening some audio or vide, etc. it wil be recorded in the video, otherwise the video is going to be in silence.
     By default the video is going to be stored in =/tmp/screencast.mp4=, If you want to record multiple videos the script is going to override the last video stored.

   - *Usage*: Run =hypr-screenrecorder= in the terminal or as a keybind. It will be appear the tofi menu to select the required option.

* Installation
These scripts can be installed using the =install.sh= script provided in the main directory of the repository. 

#+BEGIN_SRC shell
# Install scripts from the tools directory
./install.sh tools
#+END_SRC

* Contributing
Contributions are welcome! Please see the main repository's =README.org= for contribution guidelines.

Thank you for using these scripts!
