#+TITLE: General Linux Tools
#+AUTHOR: Linuxero (linuxeando) / Javier Pacheco
#+DATE: 2024-07-27
#+OPTIONS: toc:nil

* Overview
The `tools` directory hosts a collection of miscellaneous shell scripts designed to simplify and automate various tasks on Linux systems. These scripts are not specific to any window manager and can be useful in a variety of contexts.

* Scripts

1. fzmount
   - *Description*: A mount usb drives and android phones using fzf.
   - *Usage*: Run =fzmount= in the terminal, it'll open a fzf menu for mount or umount devices.

* Installation
These scripts can be installed using the =install.sh= script provided in the main directory of the repository. 

#+BEGIN_SRC shell
# Install scripts from the tools directory
./install.sh tools
#+END_SRC

* Usage
Each script includes usage instructions in the comments at the top. You can run a script directly from the terminal or integrate it into your workflow.

* Contributing
We welcome contributions! If you'd like to contribute, please see the main repository's `README.org` for guidelines.
